blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/Synthience/Synthience/discussions/categories/feature-requests
      about: Share and vote on feature requests for Synthience
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=Synthience.synthience-cline&ssr=false#review-details
      about: Enjoying Synthience? Leave a review here!
